[allowlist]
description = "Allow placeholder/example secrets"
regexes = [
  '''sk_test_[xX]{5,}''',
  '''pk_test_[xX]{5,}''',
  '''whsec_[xX]{5,}''',
  '''sk-ant-[xX]{5,}''',
  '''sk-or-v1-[xX]{5,}''',
  '''ghp_[xX]{5,}''',
  '''github_pat_[xX]{5,}''',
  '''Ov23li_[xX]{5,}''',
  '''phc_[xX]{5,}''',
  '''phx_[xX]{5,}''',
  '''re_[xX]{5,}''',
  '''fc-[xX]{5,}''',
  '''apify_api_[xX]{5,}''',
  '''sk_test_placeholder''',
  '''sk_test_\\.{3,}''',
  '''pk_test_\\.{3,}''',
  '''whsec_\\.{3,}''',
  '''sk-ant-\\.{3,}''',
  '''sk-or-v1-\\.{3,}''',
  '''ghp_\\.{3,}''',
  '''github_pat_\\.{3,}''',
  '''Ov23li_\\.{3,}''',
  '''phc_\\.{3,}''',
  '''phx_\\.{3,}''',
  '''re_\\.{3,}''',
  '''fc-\\.{3,}''',
  '''apify_api_\\.{3,}''',
]
